name: My First Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 23ds3000034@ds.study.iitm.ac.in
        run: echo "Hello, world! This is a test run for Shivam."
